services:
  - type: web
    name: imgproxy
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: ./docker
    envVars:
      - key: IMGPROXY_KEY
        sync: false
      - key: IMGPROXY_SALT
        sync: false

